// AUTO-GENERATED by scripts/extract-help-articles.py — do not edit by hand.
// Source: ShipBots help centers (help.shipbots.com / helpportal.shipbots.com).
// Re-run the script to refresh after the articles change.

export type HelpBlock =
  | { type: 'h' | 'p' | 'li' | 'callout'; text: string }
  | { type: 'img'; src: string };

export interface HelpArticle {
  key: string;
  title: string;
  url: string;
  blocks: HelpBlock[];
}

export const HELP_ARTICLES: Record<'appdot' | 'portal', HelpArticle[]> =
{
  "appdot": [
    {
      "key": "login",
      "title": "Log into your account",
      "url": "https://help.shipbots.com/your-account/v8Kxw2WLcHZgCR6Pyqq7MW/log-into-your-shipbots-account/nvwrJGTCsNBPrQbFwPKfcw",
      "blocks": [
        {
          "type": "p",
          "text": "Please go to www.shipbots.com/login or https://app.shiphero.com"
        },
        {
          "type": "p",
          "text": "Enter the Username & Password and you will be taken to the dashboard."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F2ae53edd-329a-4565-86d7-da432ff16bb6%2FLogin.gif&blockId=202e9a60-44ff-42fc-ab28-96e5204487de&projectId=2416"
        }
      ]
    },
    {
      "key": "connect",
      "title": "Connect your e-commerce platform",
      "url": "https://help.shipbots.com/your-account/v8Kxw2WLcHZgCR6Pyqq7MW/connect-your-stores-or-sales-platforms-with-shipbots-/uAPn9JhZQV5fH936JZNqW5",
      "blocks": [
        {
          "type": "h",
          "text": "Introduction"
        },
        {
          "type": "p",
          "text": "Connect your online store to the ShipBots platform. This is the best way to add products to ShipBots and synchronize your online inventory. Manage your business seamlessly by syncing the two platforms - online sales to offline fulfillment. You can connect as many stores as you wish."
        },
        {
          "type": "h",
          "text": "Access Store Connection"
        },
        {
          "type": "p",
          "text": "Navigate to the My Account tab and select the Stores option from the dropdown menu. This will display the number of stores you have connected."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F4d6a56a4-8078-4193-bb1d-9ee4a060c75c%2F80c0de41-6e10-4b80-85b5-222b5546d21b.jpeg?table=block&id=1e3767cb-7394-435b-ae5d-95ba6eec8b91&cache=v2"
        },
        {
          "type": "h",
          "text": "Add a New Store"
        },
        {
          "type": "p",
          "text": "Click on the plus sign labeled Add a New Store. You'll find several major stores that are commonly used by clients listed here. If your store isn't listed, contact your account manager for possible integration solutions."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F4d6a56a4-8078-4193-bb1d-9ee4a060c75c%2F3b9aba58-7371-42dc-ae6b-bf1c750246df.jpeg?table=block&id=fed930d7-32ab-4a91-828e-d13bbcb4d79b&cache=v2"
        },
        {
          "type": "h",
          "text": "Selecting Your Store"
        },
        {
          "type": "p",
          "text": "For demonstration, let's take Shopify as an example. Clicking on Shopify will guide you through each step of the process."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F4d6a56a4-8078-4193-bb1d-9ee4a060c75c%2F234f29bb-81e4-4140-bcc1-f9308cdb86aa.jpeg?table=block&id=df048cf3-ad99-4ae3-a0e0-a93c828e6ede&cache=v2"
        },
        {
          "type": "callout",
          "text": "Connect as many stores as you like"
        },
        {
          "type": "h",
          "text": "Add details of store and sync settings"
        },
        {
          "type": "p",
          "text": "Follow these steps to start the synchronization process."
        },
        {
          "type": "li",
          "text": "Fill in your Shopify Store Name. You will get that from Shopify settings."
        },
        {
          "type": "li",
          "text": "Sync setting for Products & Orders by checking Download Products and Orders that are created in shopify."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F4cf0ecd3-dd40-43dc-8cdf-5b23d3f48c3a%2Fd12.gif&blockId=a5fc8249-9247-4eba-a857-6e8e10af0695&projectId=2416"
        },
        {
          "type": "li",
          "text": "Select the starting Inventory number."
        },
        {
          "type": "li",
          "text": "Select \"Match what is in Shopify\" by clicking the option."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fb8c0c54a-bb91-49c3-838b-f805ddf02dc6%2Fezgif.com-gif-maker_%282%29.gif&blockId=37e092b3-9056-4971-8f85-92aec8f69642&projectId=2416"
        },
        {
          "type": "li",
          "text": "Fill this if you don’t want to import orders before a particular order id."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F4d6a56a4-8078-4193-bb1d-9ee4a060c75c%2Fd5cd6c54-70aa-4451-b048-cf2451fc287d.jpeg?table=block&id=810379cc-dbe1-41f0-8c76-1a4b626ef30d&cache=v2"
        },
        {
          "type": "li",
          "text": "Finally, click on Connect to save. This will take you to Shopify for the next steps."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F4d6a56a4-8078-4193-bb1d-9ee4a060c75c%2Fd0b88d74-ae4c-4a76-8bf5-c807a51d258d.jpeg?table=block&id=51313dd7-518e-4f98-834f-c0626122b78c&cache=v2"
        },
        {
          "type": "callout",
          "text": "Important Notice: Once your products have been transferred to ShipBots, please ensure that all the SKU numbers and Names are the same in both ShipBots and Shopify. Otherwise, you may face Inventory discrepancies and the orders may not be visible."
        }
      ]
    },
    {
      "key": "inventory",
      "title": "Send us your inventory",
      "url": "https://help.shipbots.com/your-inventory/aqKxnf3cBT2CiNS2xGsgHD/create-a-po-to-send-your-inventory/76GRZeCiKYc9fYCLvTfmad",
      "blocks": [
        {
          "type": "h",
          "text": "Introduction"
        },
        {
          "type": "p",
          "text": "Efficient inventory management starts with a clear process for creating Purchase Orders (P.O.s). ShipBots offers a user-friendly platform for this critical task."
        },
        {
          "type": "p",
          "text": "This guide details how to generate a P.O., which is how you send ShipBots your product directly from any vendor to add to the warehouse Inventory."
        },
        {
          "type": "h",
          "text": "Navigating to Purchase Orders"
        },
        {
          "type": "p",
          "text": "To begin, under the Purchase Orders tab, click on All Purchase Orders from the dropdown menu. This is where you'll create new P.O.s and manage existing ones."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F93771e98-f3b9-4274-99d7-813313919d84%2F50d13701-49ab-41ac-980b-9b7bb792b960.jpeg?table=block&id=dbcbb18e-f2b9-4c58-aa9d-533226b88d09&cache=v2"
        },
        {
          "type": "h",
          "text": "Initiating a New Purchase Order"
        },
        {
          "type": "p",
          "text": "Click the Create a Purchase Order button. This action opens a form to enter P.O. details."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F93771e98-f3b9-4274-99d7-813313919d84%2F9517eb7b-7530-4208-a29c-622de26452c7.jpeg?table=block&id=76b56183-e428-4ae3-ac98-906aecceb8bc&cache=v2"
        },
        {
          "type": "h",
          "text": "Selecting a Vendor"
        },
        {
          "type": "p",
          "text": "Choose a vendor from the dropdown list."
        },
        {
          "type": "p",
          "text": "If you're the supplier, select your account name to indicate you're the inventory source."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F7e0e82ef-3588-47e6-8677-e054774b8ad6%2Fb12.gif&blockId=6cf738e1-797b-4631-9734-2ef172ddbd7a&projectId=2416"
        },
        {
          "type": "h",
          "text": "Specifying the Warehouse"
        },
        {
          "type": "p",
          "text": "Select ShipBots - Primary or your relevant warehouse from the list to ensure correct inventory placement."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F93771e98-f3b9-4274-99d7-813313919d84%2F500a2e22-ffd4-48aa-bf55-ddd8d2cb5896.jpeg?table=block&id=25427fbe-a8a7-4e91-9bfb-efd296d4ff0e&cache=v2"
        },
        {
          "type": "h",
          "text": "Adding Products"
        },
        {
          "type": "p",
          "text": "Type the product name or SKU in the Products section’s search. Select the correct item from the suggestions. If an item isn't listed, verify its presence in your inventory system first."
        },
        {
          "type": "p",
          "text": "Repeat the product addition steps for each item."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fae8bc2f5-ec1f-4167-8902-c5dae73bf2e7%2Fb345.gif&blockId=aca30112-3382-4d00-870b-c6b1233cf5e8&projectId=2416"
        },
        {
          "type": "h",
          "text": "Determining Quantities"
        },
        {
          "type": "p",
          "text": "After selecting a product, input the desired quantity. To allow pre-orders before stock arrives, set a sell ahead quantity."
        },
        {
          "type": "p",
          "text": "If your manufacturer uses a different SKU, enter it under Manufacturer SKU."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F0f2717c4-36cf-455a-b480-c99f5866c6c2%2Fb67.gif&blockId=aa667e31-4d18-47aa-8ba1-a116a915d09d&projectId=2416"
        },
        {
          "type": "h",
          "text": "Managing Multiple Products"
        },
        {
          "type": "p",
          "text": "If a shipment has multiple boxes, use one master tracking number. Create separate P.O.s for distinct shipments."
        },
        {
          "type": "h",
          "text": "Reviewing and Saving"
        },
        {
          "type": "p",
          "text": "Check all details for accuracy, then hit Save. This step is crucial to inventory tracking and accuracy."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F93771e98-f3b9-4274-99d7-813313919d84%2Ffc7b74c2-311c-4a7b-8480-699c2d81e758.jpeg?table=block&id=a153daa0-d655-44cb-8523-755bab182c3e&cache=v2"
        },
        {
          "type": "h",
          "text": "Editing a Purchase Order"
        },
        {
          "type": "p",
          "text": "A new Purchase Order will be generated where you can edit some details. If changes are needed, select the P.O. from the list, make edits, and save again."
        },
        {
          "type": "p",
          "text": "On the right, you'll notice a fixed PO ID and an editable PO Number to align with your supplier's PO number or to make one that's memorable for you. Remember to hit the Save button to lock in your updates."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F93771e98-f3b9-4274-99d7-813313919d84%2F108ecc42-c0f3-4544-ae5b-fd2e062f9ac8.jpeg?table=block&id=c09ee0f9-3066-4016-a962-537ab33f75bc&cache=v2"
        },
        {
          "type": "h",
          "text": "Adding Tracking Information"
        },
        {
          "type": "p",
          "text": "Add the tracking number provided by your supplier to the P.O. as soon as possible. For drop-offs, enter Drop Off in the tracking field to maintain accuracy."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F93771e98-f3b9-4274-99d7-813313919d84%2F92d7f8b9-151a-47ec-a54e-cc5f43163bd4.jpeg?table=block&id=d702846c-561a-4266-ad98-a1f5b15b7e8a&cache=v2"
        },
        {
          "type": "h",
          "text": "Intimate ShipBots When it will get the Product"
        },
        {
          "type": "callout",
          "text": "Remember to Intimate ShipBots about when to expect the delivery. See how to Schedule A Drop-off to the Warehouse"
        },
        {
          "type": "p",
          "text": "With these steps, creating a P.O. in ShipBots should be straightforward. Regularly save your work and update tracking information promptly to keep your inventory management on track."
        },
        {
          "type": "callout",
          "text": "Best Practices: Before adding products, confirm they're listed in your ShipBots inventory. Edit P.O.s before receiving items to avoid inventory issues. If errors arise, check product details and consult ShipBots’ support if needed."
        }
      ]
    },
    {
      "key": "orders",
      "title": "Create a manual order",
      "url": "https://help.shipbots.com/your-orders/cMLykrTnrpyCzkTJPJ3T4N/%F0%9F%9B%BB-create-a-manual-order--pick-up-order/uNDsy8ErYZkuFLtfTmr7Uc",
      "blocks": [
        {
          "type": "h",
          "text": "Introduction"
        },
        {
          "type": "p",
          "text": "Usually, orders that you receive on your connected online store will be automatically synced. In case you want to add an order manually, you can follow these steps."
        },
        {
          "type": "h",
          "text": "Accessing the Order Creation Page"
        },
        {
          "type": "p",
          "text": "To begin, under the Orders tab, click on Create An Order from the dropdown menu to see your SKU list."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2Fdb91f3c2-4ab5-44d7-b186-03db24d14478%2Ff7beabc7-2ed1-4189-89ac-39d309f30ab7.jpeg?table=block&id=b2ef86d0-238e-4514-a532-d06e9b32df78&cache=v2"
        },
        {
          "type": "h",
          "text": "Entering Customer Shipping Information"
        },
        {
          "type": "p",
          "text": "The Create An Order page presents a form ready for the customer’s shipping details. Fill in each field thoughtfully, including the recipient's full name, company, address specifics, and contact information."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2Fdb91f3c2-4ab5-44d7-b186-03db24d14478%2F74d2ffda-144e-4557-8f1d-d9c4d6c6e8e5.jpeg?table=block&id=87a25842-6780-4576-816b-d562ab417c3f&cache=v2"
        },
        {
          "type": "h",
          "text": "Choosing a Shipping Method"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F7f87e828-86da-4f14-ba06-d9006726e373%2Fe12.gif&blockId=dd38b81b-53c3-4b02-a328-99567999b273&projectId=2416"
        },
        {
          "type": "p",
          "text": "Moving on to shipping, you can tailor the delivery to the customer's preference. Match the service level with the customer's needs by selecting the appropriate shipping timeframe from the Method dropdown and the Carrier."
        },
        {
          "type": "p",
          "text": "For cost efficiency, Cheapest is a selectable option under the Carrier dropdown. Make sure to select Ever as the method for this case."
        },
        {
          "type": "h",
          "text": "Adding Products to the Order and set Quantity"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fda5f435b-0a88-4b46-9ff7-518740ce5738%2Fe36.gif&blockId=d048e88f-59af-4875-a58c-05fe90d801d8&projectId=2416"
        },
        {
          "type": "p",
          "text": "Add products to the order using the provided search bar. Inputting a product name or SKU will bring up matching items from your inventory. Select the desired product, enter the quantity, and remember to review your choices for accuracy before clicking Save order to save your changes."
        },
        {
          "type": "p",
          "text": "That’s all! Your manual order is now created and visible on the Orders Listing page."
        },
        {
          "type": "h",
          "text": "Add your policy for Local Delivery"
        }
      ]
    },
    {
      "key": "orders-nav",
      "title": "How to navigate the orders page",
      "url": "https://help.shipbots.com/your-orders/cMLykrTnrpyCzkTJPJ3T4N/understanding-orders-list-page/v1LWZCQjzM7anqpb1CfbQM",
      "blocks": [
        {
          "type": "h",
          "text": "Introduction"
        },
        {
          "type": "p",
          "text": "The Order Listing page on Shipbots is a comprehensive interface for viewing all your Orders along with their fulfillment status. You can search, filter for Orders and update details. This guide will walk you through each feature of the Oder Listing Page to manage your Orders efficiently."
        },
        {
          "type": "h",
          "text": "Accessing Orders"
        },
        {
          "type": "p",
          "text": "To begin, under the Orders tab, click on Manage Orders from the dropdown menu to access your Orders Listing page"
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F754e052a-ca3b-4d37-b365-ce6d416e48b0%2F054a8f01-c4fa-4417-b928-1ee5433ba0de.jpeg?table=block&id=d8e988f7-f1b5-4b42-ab4c-25e0d89d307e&cache=v2"
        },
        {
          "type": "h",
          "text": "Viewing All Your Orders"
        },
        {
          "type": "p",
          "text": "On the Orders Listing page you see a list of all your Orders and all actions that can be performed."
        },
        {
          "type": "h",
          "text": "Filtering Orders"
        },
        {
          "type": "p",
          "text": "Apply filters to find Orders with Specific status and properties like Fulfillment Status and Order Date etc. These filters are great for managing a large number of Orders by allowing you to access Orders based on specific criteria."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F754e052a-ca3b-4d37-b365-ce6d416e48b0%2Febb033f2-92dc-49c3-9a20-2b298cd2003b.jpeg?table=block&id=842e3204-3cb2-432e-ae1c-4ad1091a3363&cache=v2"
        },
        {
          "type": "p",
          "text": "This table shows you all of your Orders, their Shipping Status and Ship Date etc."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F754e052a-ca3b-4d37-b365-ce6d416e48b0%2F0755b00f-c956-423e-811c-b736ecdd6c2e.jpeg?table=block&id=9fccca86-38d8-4622-a129-a464d31b1957&cache=v2"
        },
        {
          "type": "h",
          "text": "Pick Data to be shown in Table columns"
        },
        {
          "type": "p",
          "text": "You can change which data is visible in table. Click Column Visibility to manage that."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F754e052a-ca3b-4d37-b365-ce6d416e48b0%2F1249a035-e90f-400f-ac9c-9c161ea83225.jpeg?table=block&id=e5fe1c2c-7802-45f2-a020-e71e8a17e638&cache=v2"
        },
        {
          "type": "p",
          "text": "Already visible columns are in yellow. Click any to toggle what is to be shown in the table."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F754e052a-ca3b-4d37-b365-ce6d416e48b0%2Faf714da9-36f4-48c1-8572-9e9e47b94569.jpeg?table=block&id=eb7b072a-d51a-42ef-b35c-ec9543048722&cache=v2"
        },
        {
          "type": "h",
          "text": "Search Orders"
        },
        {
          "type": "p",
          "text": "Use the Search feature to quickly find any specific item you have sold."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Faa52b269-953a-4582-a3e1-662ed78e67f3%2FO2.png&blockId=17f0cd2c-a8f1-445e-ac4d-917faf441667&projectId=2416"
        },
        {
          "type": "p",
          "text": "Select the #OrderNo link to go to Order Details page"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Facbb22d7-e958-413e-911b-7c73de4b5154%2FO3.png&blockId=2819b79e-90e9-40d6-b56e-38edab391fa0&projectId=2416"
        },
        {
          "type": "p",
          "text": "View and Update Order details as needed."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fhiimg.20paths.com%2Fhighlight%2F754e052a-ca3b-4d37-b365-ce6d416e48b0%2F42297559-e5f4-4b4b-988d-a9647e093a06.jpeg?table=block&id=e4bf56ad-a31a-441d-afbd-c88a5ac580f6&cache=v2"
        },
        {
          "type": "p",
          "text": "To learn more on how to Update Order Items:"
        }
      ]
    }
  ],
  "portal": [
    {
      "key": "login",
      "title": "Log into your account",
      "url": "https://helpportal.shipbots.com/your-account/6jNCBCviCPoG47mCb3pWKQ/log-into-your-shipbots-account/6jNCBCviCPPTxVwo2seNZR",
      "blocks": [
        {
          "type": "p",
          "text": "Please go to www.shipbots.com/portal"
        },
        {
          "type": "p",
          "text": "Enter the Username & Password and you will be taken to the dashboard."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F83bab407-baf5-45ec-9099-195c9d76e9e6%2FCleanShot_2026-04-23_at_16.41.072x.png&blockId=34bdd196-d806-8007-86cf-e7e341e8347d&projectId=4278"
        }
      ]
    },
    {
      "key": "connect",
      "title": "Connect your e-commerce platform",
      "url": "https://helpportal.shipbots.com/your-account/6jNCBCviCPoG47mCb3pWKQ/connect-your-stores-or-sales-platforms-with-shipbots-/6jNCBCviCQAe1PRUaEcFRa",
      "blocks": [
        {
          "type": "h",
          "text": "Introduction"
        },
        {
          "type": "p",
          "text": "Connect your online store to the ShipBots platform. This is the best way to add products to ShipBots and synchronize your online inventory. Manage your business seamlessly by syncing the two platforms - online sales to offline fulfillment. You can connect as many stores as you wish."
        },
        {
          "type": "h",
          "text": "Access Store Connection"
        },
        {
          "type": "p",
          "text": "Navigate to the Stores tab and select the Add Store option in the top right corner of your screen. This will display the different stores you may integrate."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F85cb6cfa-b219-450a-ad77-8b3308ed5601%2FCleanShot_2026-04-23_at_16.59.40.gif&blockId=34cdd196-d806-80a5-8b97-e83191bf10c6&projectId=4278"
        },
        {
          "type": "h",
          "text": "How to Connect your Shopify Store"
        },
        {
          "type": "p",
          "text": "Select Shopify from the dropdown."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2F3plclientportal.zendesk.com%2Fhc%2Farticle_attachments%2F27522089993229?table=block&id=34cdd196-d806-80a3-879e-c0b12facb068&cache=v2"
        },
        {
          "type": "p",
          "text": "On the modal that pops up click on \"Visit Shopify App Store to connect your store.\""
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2F3plclientportal.zendesk.com%2Fhc%2Farticle_attachments%2F27522089999245?table=block&id=34cdd196-d806-8025-9737-c3e1040d8e2f&cache=v2"
        },
        {
          "type": "p",
          "text": "Follow the instructions on Shopify App Store to install \"ShipHero Inventory & Shipping\" app."
        },
        {
          "type": "p",
          "text": "On your Shopify account authorize the app installation."
        },
        {
          "type": "p",
          "text": "After a couple of minutes (your orders and products are being downloaded into the system) you will see the Shopify store connection in the Portal (you can try refreshing the portal every couple of minutes.)"
        },
        {
          "type": "h",
          "text": "How to Connect Your Amazon Store"
        },
        {
          "type": "li",
          "text": "Locate the Add Store dropdown and Select Amazon."
        },
        {
          "type": "li",
          "text": "Complete the form and click Connect My Amazon Store."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2F3plclientportal.zendesk.com%2Fhc%2Farticle_attachments%2F27327244837901?table=block&id=34cdd196-d806-80a8-8188-e04ae7d62495&cache=v2"
        },
        {
          "type": "li",
          "text": "You must authorize the Portal for the new API on the Amazon page. You will be redirected back to the Portal afterward."
        },
        {
          "type": "li",
          "text": "Amazon may send you an email to confirm our access. If so, please follow the instructions in the email to complete the process."
        },
        {
          "type": "li",
          "text": "Review your Handling Time in Amazon to prevent late orders."
        },
        {
          "type": "h",
          "text": "How to Connect Etsy"
        },
        {
          "type": "li",
          "text": "Locate the Add Store dropdown and Select Etsy."
        },
        {
          "type": "li",
          "text": "Enter your Etsy store name and click Connect My Etsy Store."
        },
        {
          "type": "h",
          "text": "How to Connect BigCommerce"
        },
        {
          "type": "p",
          "text": "To connect your store to the Portal, you’ll need your Store Hash. Once you have your Store Hash, enter it into the Bigcommerce connection form and press the Connect My Bigcommerce Store button."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fsfkb.wpengine.com%2Fwp-content%2Fuploads%2F2021%2F07%2Fimage-2.png?table=block&id=34cdd196-d806-801a-b4d2-d52de735ae8f&cache=v2"
        },
        {
          "type": "h",
          "text": "Where do I find my Store Hash?"
        },
        {
          "type": "p",
          "text": "Follow the steps below to find your Store Hash in BigCommerce"
        },
        {
          "type": "li",
          "text": "Log in to your BigCommerce admin panel"
        },
        {
          "type": "li",
          "text": "Go to this URL: https://manage.bigcommerce.com/account/stores/"
        },
        {
          "type": "li",
          "text": "Scroll to the Details section and look for the Permanent Address."
        },
        {
          "type": "li",
          "text": "The Store Hash will be the value after https://store- and before .mybigcommerce.com"
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fsfkb.wpengine.com%2Fwp-content%2Fuploads%2F2020%2F05%2FScreen-Shot-2020-05-01-at-3.07.19-PM.png?table=block&id=34cdd196-d806-805f-bf77-e9878ef46ed2&cache=v2"
        },
        {
          "type": "p",
          "text": "Be sure to map your BigCommerce statuses."
        },
        {
          "type": "h",
          "text": "How to Connect WooCommerce"
        },
        {
          "type": "p",
          "text": "You'll need a few things to connect your WooCommerce store to the Portal. The connection form requires the following fields:"
        },
        {
          "type": "h",
          "text": "Store Name"
        },
        {
          "type": "p",
          "text": "This is just a descriptive value for the connection. It can be anything, for example, “My Vintage Clothing Store.”"
        },
        {
          "type": "h",
          "text": "Store URL"
        },
        {
          "type": "p",
          "text": "This should be the full URL of your store. For example, if Google were your WooCommerce store, you would enter “https://www.google.com/” in this field."
        },
        {
          "type": "h",
          "text": "Consumer Key and Consumer Secret"
        },
        {
          "type": "p",
          "text": "You’ll need to provide us with these values so that we can connect to your WooCommerce store. Follow the steps below to get them."
        },
        {
          "type": "li",
          "text": "Log in to your WordPress admin panel."
        },
        {
          "type": "li",
          "text": "Click WooCommerce in the menu."
        },
        {
          "type": "li",
          "text": "Click Settings and then select the API tab."
        },
        {
          "type": "li",
          "text": "The “Enable the REST API” should be turned on."
        },
        {
          "type": "li",
          "text": "Click Keys/Apps and then click Add Key."
        },
        {
          "type": "li",
          "text": "Add a Description."
        },
        {
          "type": "li",
          "text": "For Permissions, select Read/Write"
        },
        {
          "type": "li",
          "text": "Click Generate API Key"
        },
        {
          "type": "li",
          "text": "Copy your “Consumer Key” and “Consumer Secret” into the corresponding fields in the Portal form. Once these fields are filled out, click the “Connect my WooCommerce store” button on the Portal, and your store will be connected."
        },
        {
          "type": "li",
          "text": "Lastly, please map your Woocommerce statuses to avoid issues while shipping."
        },
        {
          "type": "h",
          "text": "How to Connect eBay"
        },
        {
          "type": "li",
          "text": "Locate the Add Store dropdown and select eBay."
        },
        {
          "type": "li",
          "text": "Complete the form and click Connect My eBay Store."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2Fsfkb.wpengine.com%2Fwp-content%2Fuploads%2F2021%2F08%2FScreen-Shot-2021-08-27-at-9.02.30-AM-1024x600.png?table=block&id=34cdd196-d806-80bd-9590-ea452ba9c73e&cache=v2"
        },
        {
          "type": "h",
          "text": "How to Connect Walmart"
        },
        {
          "type": "li",
          "text": "Locate the Add Store dropdown and Select Walmart."
        },
        {
          "type": "li",
          "text": "Complete the form below and click Connect My Walmart Store."
        },
        {
          "type": "li",
          "text": "If you need to add the warehouse as a seller, please go ahead and enter the 3PL warehouse address and follow these steps."
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2F3plclientportal.zendesk.com%2Fhc%2Farticle_attachments%2F26866691608973?table=block&id=34cdd196-d806-806b-bbba-cdc880a34f11&cache=v2"
        },
        {
          "type": "h",
          "text": "How to Connect BestBuy Canada"
        },
        {
          "type": "li",
          "text": "Locate the Add Store dropdown and Select BestBuy Canada."
        },
        {
          "type": "li",
          "text": "Login into https://bby-dev.mirakl.net/marketplace-dashboard/"
        },
        {
          "type": "li",
          "text": "API key name is “Best Buy Canada dev account“"
        },
        {
          "type": "img",
          "src": "https://www.notion.so/image/https%3A%2F%2F3plclientportal.zendesk.com%2Fhc%2Farticle_attachments%2F26866662879885?table=block&id=34cdd196-d806-80cc-b660-e93d94dfada8&cache=v2"
        },
        {
          "type": "h",
          "text": "API connection"
        },
        {
          "type": "p",
          "text": "If you use an eCommerce store we do not directly integrate with, you can still use the Portal. Instead of connecting a store, please create an API connection to send Portal orders and products. Please request your API keys by emailing us at support@shipbots.com"
        }
      ]
    },
    {
      "key": "inventory",
      "title": "Send us your inventory",
      "url": "https://helpportal.shipbots.com/your-inventory/6jNCBCviCPJAaQ7aryFg5n/how-do-i-send-inventory-to-shipbots/7vJSfUa34KxGgx3ofL3afd",
      "blocks": [
        {
          "type": "callout",
          "text": "Summary: This article explains how to send inventory to ShipBots by: (1) creating a Shipping Plan in the portal, adding products, confirming quantities, selecting delivery type (boxes or pallets), and generating the packing list with a PO number, then (2) booking a warehouse appointment at www.shipbots.com/wro using that PO number."
        },
        {
          "type": "p",
          "text": "For General receiving guidelines please click here."
        },
        {
          "type": "h",
          "text": "Step #1: Create a Shipping Plan in your portal"
        },
        {
          "type": "p",
          "text": "This step will allow us to understand what you are bringing to our warehouse. Items that are not in your shipping plan won’t be able to be added to your inventory, so it is important that all items are in our system."
        },
        {
          "type": "p",
          "text": "To create a shipping plan, log in to your account first:"
        },
        {
          "type": "p",
          "text": "www.shipbots.com/portal"
        },
        {
          "type": "p",
          "text": "Once you are logged in, navigate to the Shipping Plan section and click on Create a Shipping Plan. Confirm the location you are sending inventory to and click Continue"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F7ce5fcb6-eafe-480c-8a40-86e0303b242b%2FCleanShot_2026-04-23_at_15.17.00.gif&blockId=34bdd196-d806-80c6-bdc3-fca635db6e0f&projectId=4278"
        },
        {
          "type": "p",
          "text": "The next section will allow you to insert the products to include in the plan. These should be the products you intend to send to us."
        },
        {
          "type": "p",
          "text": "You can search them by Product Name, SKU or barcode."
        },
        {
          "type": "callout",
          "text": "Note: If you already connected your eCommerce platform (ie, Shopify, Amazon etc..), your products should appear automatically. If you are not connecting an eCommerce platform, you should create your products before creating a Shipping Plan."
        },
        {
          "type": "p",
          "text": "In the next step, enter the itemsto send to us and confirm thequantity."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F8fe055d9-c98c-4316-a9ec-64a1385fa061%2FCleanShot_2026-04-23_at_15.24.05.gif&blockId=34bdd196-d806-80f7-bc92-c580bb121d65&projectId=4278"
        },
        {
          "type": "p",
          "text": "Once your products have been confirmed, proceed with letting us know how your items will arrive. There’s two options: Boxes (small parcels) or Pallets. Select the configuration that best matches your delivery."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fba0b75a1-fe1d-48be-b2cd-89cc5708a7a1%2FCleanShot_2026-04-23_at_15.50.42.gif&blockId=34bdd196-d806-8071-8cee-c95678d9777e&projectId=4278"
        },
        {
          "type": "h",
          "text": "If selecting Boxes"
        },
        {
          "type": "p",
          "text": "the system will ask you to confirm the box configuration of your boxes. You will have to select the quantity of items per boxquantity per box and the quantity of boxes. If you have different box configurations, you can click on the three buttons on the right hand side for more options."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F054fe378-c5e6-47cb-9a71-44ce8228340e%2FCleanShot_2026-04-23_at_15.57.04.gif&blockId=34bdd196-d806-8040-a7b8-eba831cad419&projectId=4278"
        },
        {
          "type": "h",
          "text": "If selecting pallets"
        },
        {
          "type": "callout",
          "text": "If the pallet option is not available in your account, and you need it, please reach out to us to enable this option in your account at support@shipbots.com"
        },
        {
          "type": "p",
          "text": "the system will ask you if the items will come floor loadedand to confirm thepallet quantity."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F48d3e8b0-26ee-4692-9808-2e265138507d%2FCleanShot_2026-04-23_at_16.02.52.gif&blockId=34bdd196-d806-80ed-a777-d4f1041ec9de&projectId=4278"
        },
        {
          "type": "p",
          "text": "Once you are done with the pallets or box configurations, you will see an option to add notes for our warehouse. You may leave this section blank if no further instructions are needed. Click continue when ready and Generate packing list and Finish once you are done."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F9266bb99-fbe1-4b07-9f8d-687d842c80e5%2FCleanShot_2026-04-23_at_16.13.10.gif&blockId=34bdd196-d806-804a-b702-fd298bdc44d1&projectId=4278"
        },
        {
          "type": "p",
          "text": "Your PO number will be located in the top right corner of the next screen. Save this number to book an appointment with our warehouse. If you with to change this number, you can edit to anything of your choosing. This number will identify your shipment."
        },
        {
          "type": "callout",
          "text": "If you are sending us inventory across different days, the best practice would be to create a separate shipping plans for each shipment. This will help us identify which shipment had missing inventory (if any)."
        },
        {
          "type": "h",
          "text": "Step #2 Book an appointment with our warehouse"
        },
        {
          "type": "p",
          "text": "To book an appointment, please visit: www.shipbots.com/wro"
        },
        {
          "type": "p",
          "text": "The PO# you created in the last step will be required in the second page."
        },
        {
          "type": "callout",
          "text": "We understand that overseas shipments may be difficult to schedule. Please use your best date and time estimate."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F6c2f65cd-a0db-4f15-926f-7165a111bdec%2FCleanShot_2026-04-23_at_16.23.42.gif&blockId=34bdd196-d806-8077-9c58-c6e0be957c34&projectId=4278"
        }
      ]
    },
    {
      "key": "orders",
      "title": "Create a manual order",
      "url": "https://helpportal.shipbots.com/your-orders/6jNCBCviCPAy3pn2DGMBtS/%F0%9F%9B%BB-create-a-manual-order--pick-up-order/6jNCBCviCQ9irZhFvRRyq7",
      "blocks": [
        {
          "type": "h",
          "text": "Introduction"
        },
        {
          "type": "p",
          "text": "Usually, orders that you receive on your connected online store will be automatically synced. In case you want to add an order manually, you can follow these steps."
        },
        {
          "type": "h",
          "text": "Accessing the Order Creation Page"
        },
        {
          "type": "p",
          "text": "To begin, under the Orders tab, click on Orders from the menu to access your Orders Listing page"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fbbd79eec-7387-4737-86f2-7382711c71a6%2Fimage.png&blockId=37cdd196-d806-80a1-9743-f27cc4078108&projectId=4278"
        },
        {
          "type": "p",
          "text": "Once you are in the main orders page, go ahead and click the Create New Order button in the top right corner of the screen."
        },
        {
          "type": "h",
          "text": "Adding Items to the Order"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F849209b0-9c4c-43f1-9a51-afa0ba28ea51%2FCleanShot_2026-06-11_at_12.57.02.gif&blockId=37cdd196-d806-80ca-b154-fa109f22aa63&projectId=4278"
        },
        {
          "type": "p",
          "text": "The first step in creating a new order is choosing what items to ship. Click on the \"Add items\" button to search for your items. You may search by name, SKU number, or barcode. Select the items you would like to add and confirm the quantity. Once you're done, click \"Continue\"."
        },
        {
          "type": "h",
          "text": "Add Delivery Address"
        },
        {
          "type": "p",
          "text": "The next step would be to confirm the delivery address for the final recipient. Please be thorough and complete as much information as possible. You may choose to enter billing information if needed."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F59d898a3-3e8b-4981-8ada-3039ec4de586%2FCleanShot_2026-06-11_at_13.04.55.gif&blockId=37cdd196-d806-80b6-8091-feb28537a2e7&projectId=4278"
        },
        {
          "type": "h",
          "text": "Choosing a Shipping Method and Order Details"
        },
        {
          "type": "p",
          "text": "You may choose to elect an order number of your choosing. If left blank, the system will auto-generate an order number."
        },
        {
          "type": "p",
          "text": "Moving on to shipping, you can tailor the delivery to the customer's preference. Match the service level with the customer's needs by selecting the appropriate shipping timeframe from the Method dropdown and the Carrier."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F92a65983-0d9d-41fd-bfb4-afbd75904540%2FCleanShot_2026-06-11_at_13.07.462x.png&blockId=37cdd196-d806-80b6-8885-c0c2079bdaf0&projectId=4278"
        },
        {
          "type": "p",
          "text": "For cost efficiency, Cheapest is a selectable option under the Carrier dropdown. Make sure to select Cheapest Including Smartpostas the method for this case."
        },
        {
          "type": "h",
          "text": "Marking and Order for pickup"
        },
        {
          "type": "p",
          "text": "If you wish to mark an order for pickup, please make sure you complete the following:"
        },
        {
          "type": "li",
          "text": "Order number: Pickup"
        },
        {
          "type": "li",
          "text": "Name of the order: Pickup"
        },
        {
          "type": "li",
          "text": "You may choose a name of the person that's picking up, their last name."
        },
        {
          "type": "li",
          "text": "For delivery address, also note: Pickup"
        },
        {
          "type": "li",
          "text": "Order details: Shipping method Generic - Generic label"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fe3deba90-e5bf-415b-9583-3b3d4ff794d8%2FCleanShot_2026-06-11_at_13.10.592x.png&blockId=37cdd196-d806-8048-b3ff-cda24105839f&projectId=4278"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F29ca8ce4-f090-47b2-870a-0c4b0ff26d1e%2FCleanShot_2026-06-11_at_13.12.072x.png&blockId=37cdd196-d806-8054-a10f-c9f876c6dc22&projectId=4278"
        },
        {
          "type": "p",
          "text": "Once your pick-up order has been entered in the system, please email our support team: support@shipbots.com to confirm the pick-up date and time."
        },
        {
          "type": "callout",
          "text": "Note: We typically need 24-hour notice to have a pickup order ready. However timing may vary based on the complexity of the order"
        }
      ]
    },
    {
      "key": "orders-nav",
      "title": "How to navigate the orders page",
      "url": "https://helpportal.shipbots.com/your-orders/6jNCBCviCPAy3pn2DGMBtS/understanding-orders-list-page/6jNCBCviCQGKnd8HrTp4E3",
      "blocks": [
        {
          "type": "h",
          "text": "Introduction"
        },
        {
          "type": "p",
          "text": "The Order Listing page on Shipbots is a comprehensive interface for viewing all your Orders along with their fulfillment status. You can search, filter for Orders and update details. This guide will walk you through each feature of the Oder Listing Page to manage your Orders efficiently."
        },
        {
          "type": "h",
          "text": "Accessing Orders"
        },
        {
          "type": "p",
          "text": "To begin, under the Orders tab, click on Orders from the menu to access your Orders Listing page"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F603f48b9-51ca-4891-843f-871da975787c%2FCleanShot_2026-06-11_at_11.52.12.gif&blockId=37cdd196-d806-804d-8d7f-ec30336616f2&projectId=4278"
        },
        {
          "type": "h",
          "text": "Viewing and Filtering Your Orders"
        },
        {
          "type": "p",
          "text": "When you open the Orders section, the system automatically applies a filter that shows only orders created in the last week. To view older orders, adjust the filter next to the search bar."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fe6e87ff5-f55d-46f2-a128-0bdb7bc75d73%2FCleanShot_2026-06-11_at_11.54.48.gif&blockId=37cdd196-d806-8040-bd18-f4f87c925a00&projectId=4278"
        },
        {
          "type": "p",
          "text": "In the top area, you will find different sections that will filter the orders according to their status. You may find orders on hold, ready to ship, not ready to ship, backordered, or shipped."
        },
        {
          "type": "p",
          "text": "Any applied filters will appear under the search bar."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fe3f6e1b2-1fe9-4153-8a80-57611257038b%2FCleanShot_2026-06-11_at_11.58.372x.png&blockId=37cdd196-d806-8071-a763-f874d35d6b72&projectId=4278"
        },
        {
          "type": "h",
          "text": "Search Orders by Item"
        },
        {
          "type": "p",
          "text": "You can find all orders associated with a specific item. In the search bar, change the dropdown from \"Orders\" to \"Item\", enter the item you're looking for, and press Enter. All orders containing that item within your current filter parameters will appear."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F9da7a65f-cbc5-4299-9390-f3b849df026b%2FCleanShot_2026-06-11_at_12.02.54.gif&blockId=37cdd196-d806-80f5-9b79-c13a44fa7b7a&projectId=4278"
        },
        {
          "type": "h",
          "text": "Pick Data to be shown in Table columns"
        },
        {
          "type": "p",
          "text": "You can change which data is visible in table. Click the “settings” icon to manage that."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F72cfb4fe-5735-453d-b254-53849d466723%2FCleanShot_2026-06-11_at_12.17.14.gif&blockId=37cdd196-d806-80be-a1ef-fb2f605d8f8c&projectId=4278"
        },
        {
          "type": "h",
          "text": "View Order data"
        },
        {
          "type": "p",
          "text": "Select the #OrderNo link to go to Order Details page"
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fbb35791a-f05a-47fe-9889-6dc2f7d5a653%2FCleanShot_2026-06-11_at_12.21.262x.png&blockId=37cdd196-d806-80e6-b2c5-da5279f7e941&projectId=4278"
        },
        {
          "type": "p",
          "text": "View and Update Order details as needed."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fc1353d06-c46d-4b35-8a75-af9e7f2360b2%2FCleanShot_2026-06-11_at_12.22.432x.png&blockId=37cdd196-d806-80e7-8052-d8e6a0007c6b&projectId=4278"
        },
        {
          "type": "p",
          "text": "If previous shipments have been sent for this particular order, the packages, and tracking numbers will appear in the top section."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F4ad091fe-9fcf-4a10-aa8b-b9e6960ed960%2FCleanShot_2026-06-11_at_12.22.432x.png&blockId=37cdd196-d806-8008-bc02-c2105d3f584d&projectId=4278"
        },
        {
          "type": "h",
          "text": "Orders Not Ready to Ship"
        },
        {
          "type": "p",
          "text": "Should there be a problem with an order, there will be indicators showing you exactly what is wrong."
        },
        {
          "type": "p",
          "text": "An order could be not ready to ship for several reasons:"
        },
        {
          "type": "p",
          "text": "Holds"
        },
        {
          "type": "p",
          "text": "The order could have a hold due to potential fraud problems, address problems, or payment problems because our staff has put the order on hold or you, the client, have put the order on hold."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Fb2691d7d-ee93-4768-ad2a-6bc138932ff4%2FCleanShot_2026-06-11_at_12.27.562x.png&blockId=37cdd196-d806-8053-8ffe-f6c59f87320b&projectId=4278"
        },
        {
          "type": "p",
          "text": "To remove holds, there are two ways to do this:"
        },
        {
          "type": "li",
          "text": "If the hold is an address hold, then a shipping address verification box will appear where you get to choose whether to ignore the address error or to edit the shipping address."
        },
        {
          "type": "li",
          "text": "If a different type of hold appears, then a button will appear in the bottom right corner where you can release the hold."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2Feb7b073a-9d05-43b3-9fb2-67f2545819f6%2FCleanShot_2026-06-11_at_12.34.202x.png&blockId=37cdd196-d806-80ea-b8bf-e2f23ffb67bf&projectId=4278"
        },
        {
          "type": "p",
          "text": "Backorders"
        },
        {
          "type": "p",
          "text": "If the order has one or more items that we don't have in the warehouse, then the entire order will not be ready to ship and will not ship until the order is complete."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F8fac8874-21a9-4534-bc0d-b32dfbe656c3%2FCleanShot_2026-06-11_at_12.36.342x.png&blockId=37cdd196-d806-8078-905a-fa38e307e604&projectId=4278"
        },
        {
          "type": "p",
          "text": "By default, orders won't ship until we have all the items in an order; however, you may choose to allow us to partial ship any order by enabling Allow Partial on an order per order basis."
        },
        {
          "type": "img",
          "src": "https://media.helpkit.co/proxy?url=https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2Fc3b2df48-fcf0-42a5-93f8-299fee68ab0f%2F4490103d-d0d9-4398-b585-231309152aae%2FCleanShot_2026-06-11_at_12.39.412x.png&blockId=37cdd196-d806-80cd-ae3d-ce2db12b31e5&projectId=4278"
        },
        {
          "type": "p",
          "text": "We have the ability to enable the allow partial option for every incoming order. However, you have to opt in for this by emailing our support team."
        }
      ]
    }
  ]
};
