/**
 * POST /api/generate-onboarding-summary
 *
 * Streams an internal team onboarding summary email generated by Claude.
 * Steps:
 *   1. Fetch full client record from Monday.com
 *   2. Search Fireflies for ALL transcripts matching the client name (all calls)
 *   3. Pull the most recent full meeting summary
 *   4. Send everything to Claude with the internal team email prompt
 *   5. Stream the response back as plain-text chunks
 *
 * Body: { clientName: string; clientBoardItemId: string; onboardingItemId?: string }
 * Response: text/plain stream
 */
import { NextRequest } from 'next/server';
import { fetchClientInfo } from '@/lib/monday';

const FIREFLIES_API_URL = 'https://api.fireflies.ai/graphql';

const TEAM_TO = 'support@shipbots.com, allen@shipbots.com, payam@shipbots.com, carmen@shipbots.com, karina@shipbots.com, alex@shipbots.com, nancy@shipbots.com, robert@shipbots.com';
const TEAM_BCC = 'andres@shipbots.com';

export { TEAM_TO, TEAM_BCC };

async function firefliesQuery(query: string, variables?: Record<string, unknown>) {
  const key = process.env.FIREFLIES_API_KEY;
  if (!key) return null;
  const res = await fetch(FIREFLIES_API_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
    body: JSON.stringify({ query, variables }),
  });
  const data = await res.json();
  if (data.errors) { console.error('Fireflies error:', data.errors); return null; }
  return data.data;
}

interface FirefliesTranscript {
  id: string;
  title: string;
  date: number;
  duration: number;
  participants: string[];
  organizer_email?: string;
  summary?: {
    overview?: string;
    action_items?: string;
    shorthand_bullet?: string;
    bullet_gist?: string;
    keywords?: string;
  };
}

async function searchFireflies(
  clientName: string,
  contactEmails: string[] = [],
  extraTerms: string[] = [],
): Promise<FirefliesTranscript[]> {
  const gqlQuery = `query ($title: String) {
    transcripts(title: $title, limit: 20) {
      id title date duration participants organizer_email
      summary { overview action_items shorthand_bullet bullet_gist keywords }
    }
  }`;

  const allTerms = [...new Set([clientName, ...extraTerms, ...contactEmails].filter(Boolean).map(s => s.trim()).filter(s => s.length > 2))];

  const results = await Promise.allSettled(
    allTerms.map(term => firefliesQuery(gqlQuery, { title: term }))
  );

  const seen = new Set<string>();
  const merged: FirefliesTranscript[] = [];

  for (const r of results) {
    if (r.status !== 'fulfilled') continue;
    for (const t of (r.value?.transcripts ?? [])) {
      if (!seen.has(t.id)) { seen.add(t.id); merged.push(t); }
    }
  }

  return merged;
}

async function getFirefliesSummary(transcriptId: string): Promise<FirefliesTranscript | null> {
  const query = `query ($id: String!) {
    transcript(id: $id) {
      id title date duration participants organizer_email
      summary { overview action_items shorthand_bullet bullet_gist keywords }
    }
  }`;
  const data = await firefliesQuery(query, { id: transcriptId });
  return data?.transcript ?? null;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildContext(client: Record<string, any>, meetings: FirefliesTranscript[], clientName: string): string {
  const lines: string[] = [];

  lines.push('=== CLIENT RECORD (Monday.com) ===');
  lines.push(`Client Name: ${clientName}`);

  const field = (label: string, val: unknown) => {
    const v = String(val ?? '').trim();
    if (v) lines.push(`${label}: ${v}`);
  };

  field('Legal Entity Name', client.legalEntity);
  field('ShipHero Name (QB Display Name)', client.shipHeroName);

  // Contacts
  field('Primary Contact Name', client.contactName);
  field('Primary Contact Email', client.contactEmail);
  field('Primary Contact Phone', client.contactPhone);
  field('Contact 2 Name', client.contact2Name);
  field('Contact 2 Email', client.contact2Email);
  field('Contact 2 Phone', client.contact2Phone);
  field('Contact 3 Name', client.contact3Name);
  field('Contact 3 Email', client.contact3Email);
  field('Contact 3 Phone', client.contact3Phone);

  // Portal
  field('Portal Login Email (AppDot / ShipHero Portal)', client.portalEmail);
  field('Portal Dropdown / AppDot Access', client.portalDropdown);
  field('ShipBots Support Portal Username', client.portalLogin);

  // Product
  field('Product Category', client.productCategory);
  field('Product Description', client.productDescription);
  field('# of SKUs', client.skuCount);
  field('E-Commerce Platforms', client.ecommercePlatforms);
  field('Current Fulfillment Method', client.currentFulfillmentMethod);
  field('Estimated Shipping Volume', client.shippingVolume);

  // Shipping
  field('Shipping Method', client.shippingMethod);
  field('Overnight/2-Day Delivery', client.overnightDelivery);
  field('Currently Fulfilling Internationally', client.internationalFulfillment);
  field('International DDU/DDP', client.internationalShippingDDUDDP);
  field('Amazon FBA', client.amazonFBA);
  field('TikTok Shop', client.tikTokShop);
  field('Lot Code / Expiration Needed', client.lotCodeExpiration);
  field('Additional Insurance / Signature Required', client.additionalInsuranceSignature);
  field('Wholesale / Outbound LTL', client.wholesaleDetails);
  field('Outbound LTL Details', client.outboundLTL);
  field('Additional Shipping Notes', client.additionalShippingNotes);

  // Packing
  field('Packaging', client.packaging);
  field('Order Inserts', client.orderInserts);
  field('Order Insert Details', client.orderInsertDetails);
  field('Kits or Bundles', client.kitsOrBundles);
  field('Pre-Bag / Pre-Pack Before Storage', client.preStorageNeeds);
  field('Notes for Packing', client.notesForPacking);
  field('Pick & Pack', client.pickAndPack);

  // Receiving / Inventory
  field('Initial Inventory Est. Delivery Date', client.initialInventoryDate);
  field('Initial Inventory Delivery Method', client.initialInventoryMethod);
  field('Initial Inventory Quantity', client.initialInventoryQty);
  field('Items Barcoded', client.itemsBarcoded);
  field('Special Storing Needs', client.initialInventoryStoringNeeds);
  field('Notes on Initial Inventory', client.notesOnInitialInventory);
  field('Notes for Receiving', client.notesForReceiving);

  // Returns
  field('Returns Process', client.returnsProcess);

  // Warehouse
  field('Warehouse Location', client.warehouseLocation);
  field('Additional Notes', client.additionalNotes);

  lines.push('');

  if (meetings.length > 0) {
    lines.push('=== ONBOARDING CALL(S) (Fireflies) ===');
    meetings.forEach((m, i) => {
      const meetDate = m.date
        ? new Date(m.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
        : '';
      lines.push(`\n--- Call ${i + 1}: ${m.title}${meetDate ? ` (${meetDate})` : ''} ---`);
      if (m.organizer_email) lines.push(`Organizer: ${m.organizer_email}`);
      if (m.participants?.length) lines.push(`Participants: ${m.participants.join(', ')}`);
      if (m.summary?.overview) lines.push(`\nOverview:\n${m.summary.overview}`);
      if (m.summary?.shorthand_bullet) lines.push(`\nKey Points:\n${m.summary.shorthand_bullet}`);
      if (m.summary?.bullet_gist) lines.push(`\nGist:\n${m.summary.bullet_gist}`);
      if (m.summary?.action_items) lines.push(`\nAction Items:\n${m.summary.action_items}`);
    });
  } else {
    lines.push('=== ONBOARDING CALL ===');
    lines.push('No matching calls found in Fireflies. Generate the email based solely on Monday.com data.');
  }

  return lines.join('\n');
}

export async function POST(req: NextRequest) {
  const { clientName, clientBoardItemId, onboardingItemId } = await req.json();
  if (!clientName || !clientBoardItemId) {
    return new Response(JSON.stringify({ error: 'Missing clientName or clientBoardItemId' }), { status: 400 });
  }

  const anthropicKey = process.env.SHIPBOTS_ANTHROPIC_KEY;
  if (!anthropicKey) {
    return new Response(JSON.stringify({ error: 'SHIPBOTS_ANTHROPIC_KEY not set' }), { status: 503 });
  }

  // 1. Fetch Monday.com client info
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let clientInfo: Record<string, any> = {};
  try {
    clientInfo = await fetchClientInfo(clientBoardItemId, onboardingItemId) as unknown as Record<string, unknown>;
  } catch (e) {
    console.warn('[generate-onboarding-summary] Monday.com fetch failed:', e);
  }

  // 2. Search Fireflies — collect all matching transcripts, sorted newest first
  let meetings: FirefliesTranscript[] = [];
  try {
    const contactEmails = [clientInfo.contactEmail, clientInfo.contact2Email, clientInfo.contact3Email].filter(Boolean) as string[];
    const extraTerms   = [clientInfo.legalEntity, clientInfo.contactName].filter(Boolean) as string[];
    const results = await searchFireflies(clientName, contactEmails, extraTerms);
    const sorted = results.sort((a, b) => (b.date ?? 0) - (a.date ?? 0));
    // Pull full summary for the most recent call
    if (sorted.length > 0) {
      const full = await getFirefliesSummary(sorted[0].id);
      meetings = full ? [full, ...sorted.slice(1)] : sorted;
    }
  } catch (e) {
    console.warn('[generate-onboarding-summary] Fireflies search failed:', e);
  }

  // 3. Build context
  const context = buildContext(clientInfo, meetings, clientName);

  // 4. System prompt
  const systemPrompt = `You are Andres from ShipBots (andres@shipbots.com). Your job is to write an internal team onboarding summary email to brief the ShipBots fulfillment team on a newly onboarded client.

You will be given:
- A client record from Monday.com with all relevant data
- One or more onboarding call summaries from Fireflies

Generate ONLY the email body (no metadata, no explanation). Start with "Subject: New Client: [Client Name]" on the first line, then a blank line, then the email body.

RULES:
- Formatting: Use **bold** for section headers and key labels. Use • bullet points with emojis as described below. Use *italic* for pending/flagged items.
- Emojis: Use throughout for visual clarity — on section headers, bullet points, and contact fields (📧 email, 📞 phone).
- Do NOT mention the ShipBots Hub — only reference "ShipHero Portal" or "AppDot" for platform info.
- Do NOT include billing details.
- Do NOT go into detail about returns — only mention Loop integration briefly in Platform & Operations if applicable.
- If details are still pending/unknown, flag clearly with: ⏳ Pending — [reason]
- Pull phone numbers from the Fireflies transcript when spoken during the call. If a phone from the transcript differs from Monday.com, note both and flag for confirmation.
- Keep each section concise but complete — the fulfillment team needs to act on this info.
- Always note the legal entity name if it differs from the brand/client name.
- TIKTOK SHOP RULE: If "TikTok Shop" is "Yes", mention TikTok Shop prominently in the opening paragraph (e.g. "including **TikTok Shop**"). In the Platform & Operations section, add a bullet: "• 🛍️ **TikTok Shop**: Orders placed under the TikTok Shop status require **same-day shipping** and will appear under the TikTok Shop status in ShipHero."
- LOT CODE RULE: If "Lot Code / Expiration Needed" is "Yes", add a bullet in Notes for Receiving: "• 🏷️ **Lot Code / Expiration Tracking**: This client requires lot code and expiration date tracking. Please ensure all receiving is done with lot codes and expiration dates recorded in ShipHero."

PORTAL DETECTION RULES:
- It is the ShipHero Portal if the transcript mentions the login is www.shipbots.com/portal
- It is AppDot (also called "advanced version", "backend software", or "legacy version" of ShipHero) if the transcript mentions giving access to the advanced/backend/legacy version
- Never use the word "Hub" when referring to these portals

EMAIL STRUCTURE:

Subject: New Client: [Client Name]

Hi team! 👋 I just onboarded [Client Name]! [One sentence: what they sell + main sales channel(s).]
[If legal entity differs from brand name: Note legal entity.]

**👤 Contact**
• [Name] — Main Contact
  📧 [email]
  📞 [phone]
[Repeat for additional contacts]

**🖥️ Platform & Operations**
• Portal: [ShipHero Portal (www.shipbots.com/portal) OR AppDot]
• Stores connected: [list platforms]
• Order management: [how orders flow]
• [Any operational notes: buffers, kitting, TikTok SLA, etc.]
• [Loop returns — one line only if applicable]

**📦 Notes for Receiving**
• 📅 [Expected arrival date and origin]
• 🚚 [How inventory is arriving — freight/pallets/boxes/courier/etc.]
• ✅ [Barcoding status]
• 🏷️ [Labeling requirements]
• 🌡️ [Special storage if applicable]
• 📋 [Any other special receiving instructions]

**📋 Notes for Packers**
• [Packaging method]
• [Custom packaging elements]
• [Shipping tiers]
• [International shipping — DDP or domestic only]
• [Insurance / signature required status]
• [Bundles/kits if applicable]
• [Anything else packers need to know]

Let me know who we should assign this account to and if you have any questions! 🙌

Andres`;

  const userMessage = `Please generate the internal team onboarding summary email for this client:\n\n${context}`;

  // 5. Stream Claude response
  const anthropicRes = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': anthropicKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 2048,
      stream: true,
      system: systemPrompt,
      messages: [{ role: 'user', content: userMessage }],
    }),
  });

  if (!anthropicRes.ok || !anthropicRes.body) {
    const err = await anthropicRes.text();
    return new Response(JSON.stringify({ error: err }), { status: 502 });
  }

  const reader = anthropicRes.body.getReader();
  const decoder = new TextDecoder();

  const stream = new ReadableStream({
    async start(controller) {
      let buffer = '';
      while (true) {
        const { done, value } = await reader.read();
        if (done) { controller.close(); break; }
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() ?? '';
        for (const line of lines) {
          if (!line.startsWith('data: ')) continue;
          const raw = line.slice(6).trim();
          if (raw === '[DONE]') continue;
          try {
            const evt = JSON.parse(raw);
            if (evt.type === 'content_block_delta' && evt.delta?.type === 'text_delta') {
              controller.enqueue(new TextEncoder().encode(evt.delta.text));
            }
          } catch { /* skip malformed */ }
        }
      }
    },
  });

  return new Response(stream, { headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
}
