/**
 * POST /api/generate-summary
 *
 * Streams a post-onboarding summary email generated by Claude.
 * Steps:
 *   1. Fetch full client record from Monday.com
 *   2. Search Fireflies for the most recent onboarding call matching the client name
 *   3. Pull the full meeting summary + action items
 *   4. Send everything to Claude (claude-sonnet-4-6) with the email-generation prompt
 *   5. Stream the response back as plain-text chunks
 *
 * Body: { clientName: string; clientBoardItemId: string; onboardingItemId?: string }
 * Response: text/plain stream of the generated email
 */
import { NextRequest } from 'next/server';
import { fetchClientInfo } from '@/lib/monday';

const FIREFLIES_API_URL = 'https://api.fireflies.ai/graphql';

// ─── Fireflies helpers ────────────────────────────────────────────────────────

async function firefliesQuery(query: string, variables?: Record<string, unknown>) {
  const key = process.env.FIREFLIES_API_KEY;
  if (!key) return null;
  const res = await fetch(FIREFLIES_API_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
    body: JSON.stringify({ query, variables }),
  });
  const data = await res.json();
  if (data.errors) { console.error('Fireflies error:', data.errors); return null; }
  return data.data;
}

interface FirefliesTranscript {
  id: string;
  title: string;
  date: number;
  duration: number;
  participants: string[];
  organizer_email?: string;
  summary?: {
    overview?: string;
    action_items?: string;
    shorthand_bullet?: string;
    bullet_gist?: string;
    keywords?: string;
  };
}

async function searchFireflies(
  clientName: string,
  contactEmails: string[] = [],
  extraTerms: string[] = [],
): Promise<FirefliesTranscript[]> {
  const gqlQuery = `query ($title: String) {
    transcripts(title: $title, limit: 20) {
      id title date duration participants organizer_email
      summary { overview action_items shorthand_bullet bullet_gist keywords }
    }
  }`;

  const allTerms = [...new Set([clientName, ...extraTerms, ...contactEmails].filter(Boolean).map(s => s.trim()).filter(s => s.length > 2))];

  const results = await Promise.allSettled(
    allTerms.map(term => firefliesQuery(gqlQuery, { title: term }))
  );

  const seen = new Set<string>();
  const merged: FirefliesTranscript[] = [];

  for (const r of results) {
    if (r.status !== 'fulfilled') continue;
    for (const t of (r.value?.transcripts ?? [])) {
      if (!seen.has(t.id)) { seen.add(t.id); merged.push(t); }
    }
  }

  return merged;
}

async function getFirefliesSummary(transcriptId: string): Promise<FirefliesTranscript | null> {
  const query = `query ($id: String!) {
    transcript(id: $id) {
      id title date duration participants organizer_email
      summary { overview action_items shorthand_bullet bullet_gist keywords }
    }
  }`;
  const data = await firefliesQuery(query, { id: transcriptId });
  return data?.transcript ?? null;
}

// ─── Context builder ──────────────────────────────────────────────────────────

function buildContext(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  client: Record<string, any>,
  meeting: FirefliesTranscript | null,
  clientName: string
): string {
  const lines: string[] = [];

  lines.push('=== CLIENT RECORD (Monday.com) ===');
  lines.push(`Client Name: ${clientName}`);

  const field = (label: string, val: unknown) => {
    const v = String(val ?? '').trim();
    if (v) lines.push(`${label}: ${v}`);
  };

  // Contacts
  field('Person of Contact', client.contactName);
  field('Contact Email', client.contactEmail);
  field('Contact Phone', client.contactPhone);
  field('Contact 2 Name', client.contact2Name);
  field('Contact 2 Email', client.contact2Email);
  field('Contact 2 Phone', client.contact2Phone);
  field('Contact 3 Name', client.contact3Name);
  field('Contact 3 Email', client.contact3Email);
  field('Contact 3 Phone', client.contact3Phone);

  // Portal
  field('Portal Login Email (AppDot)', client.portalEmail);
  field('ShipBots Support Login / Portal Username', client.portalLogin);
  field('Portal Dropdown / AppDot', client.portalDropdown);

  // Product
  field('ShipHero Name (QB Display Name)', client.shipHeroName);
  field('Product Category', client.productCategory);
  field('Product Description', client.productDescription);
  field('# of SKUs', client.skuCount);
  field('Kits or Bundles', client.kitsOrBundles);
  field('Order Inserts', client.orderInserts);
  field('Order Inserts Details', client.orderInsertDetails);
  field('Pre-Bag / Pre-Pack Before Storage', client.preStorageNeeds);
  field('Packaging', client.packaging);
  field('Notes for Packing', client.notesForPacking);

  // E-Commerce
  field('E-Commerce Platforms', client.ecommercePlatforms);
  field('Current Fulfillment Method', client.currentFulfillmentMethod);

  // Shipping
  field('Shipping Method', client.shippingMethod);
  field('Currently Fulfilling Internationally', client.internationalFulfillment);
  field('International DDU/DDP', client.internationalShippingDDUDDP);
  field('Overnight/2-Day Delivery', client.overnightDelivery);
  field('Amazon FBA', client.amazonFBA);
  field('Additional Insurance / Signature', client.additionalInsuranceSignature);
  field('Wholesale Details', client.wholesaleDetails);
  field('Outbound LTL', client.outboundLTL);
  field('Estimated Inventory Storage', client.estimatedStorage);
  field('Additional Shipping Notes', client.additionalShippingNotes);

  // Inventory / Receiving
  field('Initial Inventory Est. Delivery Date', client.initialInventoryDate);
  field('Initial Inventory Delivery Method', client.initialInventoryMethod);
  field('Initial Inventory Quantity', client.initialInventoryQty);
  field('Items Barcoded', client.itemsBarcoded);
  field('Pre-Storage / Storing Needs', client.initialInventoryStoringNeeds);
  field('Notes on Initial Inventory', client.notesOnInitialInventory);
  field('Notes for Receiving', client.notesForReceiving);

  // Returns
  field('Returns Process', client.returnsProcess);
  field('Notes for Returns', client.notesForReturns);

  // Warehouse + misc
  field('Warehouse Location', client.warehouseLocation);
  field('Additional Notes', client.additionalNotes);

  lines.push('');

  if (meeting) {
    const meetDate = meeting.date ? new Date(meeting.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : '';
    lines.push('=== ONBOARDING CALL (Fireflies) ===');
    lines.push(`Title: ${meeting.title}`);
    if (meetDate) lines.push(`Date: ${meetDate}`);
    if (meeting.organizer_email) lines.push(`Organizer: ${meeting.organizer_email}`);
    if (meeting.participants?.length) lines.push(`Participants: ${meeting.participants.join(', ')}`);
    if (meeting.summary?.overview) lines.push(`\nOverview:\n${meeting.summary.overview}`);
    if (meeting.summary?.shorthand_bullet) lines.push(`\nKey Points:\n${meeting.summary.shorthand_bullet}`);
    if (meeting.summary?.bullet_gist) lines.push(`\nGist:\n${meeting.summary.bullet_gist}`);
    if (meeting.summary?.action_items) lines.push(`\nAction Items:\n${meeting.summary.action_items}`);
    if (meeting.summary?.keywords) lines.push(`\nKeywords: ${meeting.summary.keywords}`);
  } else {
    lines.push('=== ONBOARDING CALL ===');
    lines.push('No matching call found in Fireflies. Generate the email based solely on Monday.com data.');
  }

  return lines.join('\n');
}

// ─── Main handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const { clientName, clientBoardItemId, onboardingItemId } = await req.json();
  if (!clientName || !clientBoardItemId) {
    return new Response(JSON.stringify({ error: 'Missing clientName or clientBoardItemId' }), { status: 400 });
  }

  const anthropicKey = process.env.SHIPBOTS_ANTHROPIC_KEY;
  if (!anthropicKey) {
    return new Response(JSON.stringify({ error: 'SHIPBOTS_ANTHROPIC_KEY not set' }), { status: 503 });
  }

  // 1. Fetch Monday.com client info
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let clientInfo: Record<string, any> = {};
  try {
    clientInfo = await fetchClientInfo(clientBoardItemId, onboardingItemId) as Record<string, unknown>;
  } catch (e) {
    console.warn('[generate-summary] Monday.com fetch failed:', e);
  }

  // 2. Search Fireflies
  let meeting: FirefliesTranscript | null = null;
  try {
    const contactEmails = [clientInfo.contactEmail, clientInfo.contact2Email, clientInfo.contact3Email].filter(Boolean) as string[];
    const extraTerms   = [clientInfo.legalEntity, clientInfo.contactName].filter(Boolean) as string[];
    const results = await searchFireflies(clientName, contactEmails, extraTerms);
    if (results.length > 0) {
      // Prefer the most recent call
      const sorted = results.sort((a, b) => (b.date ?? 0) - (a.date ?? 0));
      meeting = await getFirefliesSummary(sorted[0].id) ?? sorted[0];
    }
  } catch (e) {
    console.warn('[generate-summary] Fireflies search failed:', e);
  }

  // 3. Build context
  const context = buildContext(clientInfo, meeting, clientName);

  // 4. Prompt for Claude
  const systemPrompt = `You are Andres from ShipBots (andres@shipbots.com). Your job is to generate a personalized post-onboarding follow-up email for a client after their onboarding call.

You will be given:
- A client record from Monday.com with all relevant data
- An onboarding call summary from Fireflies (if found)

Generate ONLY the email body (no metadata, no explanation). Start with "Subject: ..." on the first line, then a blank line, then the email body starting with "Hi [name(s)],"

RULES:
- Tone: Professional but friendly and conversational — match Andres's natural voice. Not overly formal.
- Formatting: Use markdown for emphasis — **bold** for names/labels/action item owners, *italic* for light emphasis. Use • bullet points for lists. Do NOT use # headings.
- Platform adaptation: Only mention platforms the client actually uses. Include Shopify GIF guide instructions only for Shopify clients.
- Action items: Only include the action items section if Fireflies explicitly captured them. Do not fabricate action items.
- Credentials: Always use the client's actual email(s) from "Portal Login Email" or "Contact Email" fields for portal username. Password is always Changeme1. Hub access is always via invite (no username/password to share).
- Multiple contacts: If more than one person attended the call, address them all by first name, list all their portal login emails, attribute action items to specific people using **bold names**.
- No hallucination: Don't invent topics not discussed. If call summary doesn't mention international shipping, don't add a section about it.
- Length: Thorough but scannable. Use bullet points for lists.

EMAIL TEMPLATE STRUCTURE:
Hi [First name(s)],

Thank you for your time [today/last week/etc.] to discuss your fulfillment needs with me. As I mentioned in our call, you and I will work together until we have your stores completely set up before handing you over to your dedicated account manager.

As a recap, during our conversation we talked about our ShipBots Hub (hub.shipbots.com). The Hub is where you go to:
• Edit your profile
• Review FAQs and announcements
• Pay and view your invoices
• Contact information for our staff
• Submit Claims
• General help articles
• Schedule warehouse appointments

You should have received an invite to create your Hub account[s]. Please make sure to set [that/those] up when you get a chance.

You will also have access to our ShipBots Portal (ShipHero). Login credentials:

www.shipbots.com/portal
Username: [portal login email(s) from Monday.com]
Password: Changeme1

[Platform connection instructions — only for platforms client actually uses]

One important thing to keep in mind: a shipping plan (purchase order) must be created in the ShipBots backend before your inventory arrives so we can properly receive and log it. You can review the process on how to do so in [this video](https://www.youtube.com/watch?v=gYTDVXvqcOo).

If you'd like to review our receiving guidelines, please [click here to view](https://canva.link/8hhpa6sedxnp1rd).

[2-3 sentence paragraph covering key topics unique to this client's call]

[Action Items section — only if captured in Fireflies]

[Closing — if a follow-up call is scheduled reference it; if the client data shows "Additional Call Required" = Yes, include: "Please book your next onboarding call with me here: www.shipbots.com/onboarding"; otherwise mention scheduling a follow-up for ShipHero Portal training]

Hope you have a great [rest of your day/week/weekend]!
Thank you,
Andres`;

  const userMessage = `Please generate the post-onboarding follow-up email for this client:\n\n${context}`;

  // 5. Stream Claude response
  const anthropicRes = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': anthropicKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 2048,
      stream: true,
      system: systemPrompt,
      messages: [{ role: 'user', content: userMessage }],
    }),
  });

  if (!anthropicRes.ok || !anthropicRes.body) {
    const err = await anthropicRes.text();
    return new Response(JSON.stringify({ error: err }), { status: 502 });
  }

  // Transform Anthropic SSE stream → plain text chunks
  const reader = anthropicRes.body.getReader();
  const decoder = new TextDecoder();

  const stream = new ReadableStream({
    async start(controller) {
      let buffer = '';
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split('\n');
          buffer = lines.pop() ?? '';
          for (const line of lines) {
            if (!line.startsWith('data: ')) continue;
            const json = line.slice(6).trim();
            if (json === '[DONE]') continue;
            try {
              const event = JSON.parse(json);
              if (event.type === 'content_block_delta' && event.delta?.type === 'text_delta') {
                controller.enqueue(new TextEncoder().encode(event.delta.text));
              }
            } catch { /* skip malformed */ }
          }
        }
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8', 'X-Accel-Buffering': 'no' },
  });
}
